version: "3.9"

services:
  db:
    image: postgres:15
    container_name: avito_postgres
    restart: always
    environment:
      POSTGRES_DB: avito
      POSTGRES_USER: avito_user
      POSTGRES_PASSWORD: avito_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: avito_api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: avito_user
      DB_PASSWORD: avito_pass
      DB_NAME: avito
    ports:
      - "8080:8080"

volumes:
  pg_data:
